name: Validate Time Zone Conversions

on:
  push:
    paths:
      - input.json
      - src/main/java/TimeZoneConverter.java

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile and run Java code
        run: |
          javac src/main/java/TimeZoneConverter.java
          java -DoutputFile=output.log src/main/java/TimeZoneConverter input.json output.log

      - name: Upload output log file
        uses: actions/upload-artifact@v2
        with:
          name: output.log
          path: output.log