name: Timezone Converter

on:
  push:
    paths:
      - input.json
      - src/main/java/**/*

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and run
        run: |
          mvn clean package
          java -jar target/TimeZoneScheduling-1.0-SNAPSHOT.jar input.json